# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basin_name_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_basin_name(object):
    def setupUi(self, basin_name):
        basin_name.setObjectName("basin_name")
        basin_name.setWindowModality(QtCore.Qt.ApplicationModal)
        basin_name.resize(312, 102)
        basin_name.setMinimumSize(QtCore.QSize(312, 102))
        basin_name.setMaximumSize(QtCore.QSize(312, 102))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/title.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        basin_name.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(basin_name)
        self.centralwidget.setObjectName("centralwidget")
        self.basinname_ok_button = QtWidgets.QPushButton(self.centralwidget)
        self.basinname_ok_button.setGeometry(QtCore.QRect(10, 60, 81, 31))
        self.basinname_ok_button.setObjectName("basinname_ok_button")
        self.basinname_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.basinname_lineEdit.setGeometry(QtCore.QRect(90, 20, 201, 20))
        self.basinname_lineEdit.setObjectName("basinname_lineEdit")
        self.basinname_label = QtWidgets.QLabel(self.centralwidget)
        self.basinname_label.setGeometry(QtCore.QRect(10, 20, 72, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.basinname_label.setFont(font)
        self.basinname_label.setObjectName("basinname_label")
        basin_name.setCentralWidget(self.centralwidget)

        self.retranslateUi(basin_name)
        QtCore.QMetaObject.connectSlotsByName(basin_name)

    def retranslateUi(self, basin_name):
        _translate = QtCore.QCoreApplication.translate
        basin_name.setWindowTitle(_translate("basin_name", "Determin Your Basin Name"))
        self.basinname_ok_button.setText(_translate("basin_name", "OK"))
        self.basinname_label.setText(_translate("basin_name", "Basin Name:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    basin_name = QtWidgets.QMainWindow()
    ui = Ui_basin_name()
    ui.setupUi(basin_name)
    basin_name.show()
    sys.exit(app.exec_())
