# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'correction_factor_sheet3_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_correction_factor_sheet3(object):
    def setupUi(self, correction_factor_sheet3):
        correction_factor_sheet3.setObjectName("correction_factor_sheet3")
        correction_factor_sheet3.resize(418, 276)
        correction_factor_sheet3.setMinimumSize(QtCore.QSize(418, 276))
        correction_factor_sheet3.setMaximumSize(QtCore.QSize(418, 276))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/title.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        correction_factor_sheet3.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(correction_factor_sheet3)
        self.centralwidget.setObjectName("centralwidget")
        self.correction_factor_sheet3_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.correction_factor_sheet3_checkbox.setGeometry(QtCore.QRect(10, 10, 351, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.correction_factor_sheet3_checkbox.sizePolicy().hasHeightForWidth())
        self.correction_factor_sheet3_checkbox.setSizePolicy(sizePolicy)
        self.correction_factor_sheet3_checkbox.setObjectName("correction_factor_sheet3_checkbox")
        self.ok_equation_correction_factor_sheet3_push = QtWidgets.QPushButton(self.centralwidget)
        self.ok_equation_correction_factor_sheet3_push.setGeometry(QtCore.QRect(10, 240, 75, 23))
        self.ok_equation_correction_factor_sheet3_push.setObjectName("ok_equation_correction_factor_sheet3_push")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(False)
        self.groupBox.setGeometry(QtCore.QRect(10, 34, 381, 201))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 21, 361, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.correction_factor_sheet3_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.correction_factor_sheet3_lineEdit.setObjectName("correction_factor_sheet3_lineEdit")
        self.verticalLayout.addWidget(self.correction_factor_sheet3_lineEdit)
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        correction_factor_sheet3.setCentralWidget(self.centralwidget)

        self.retranslateUi(correction_factor_sheet3)
        QtCore.QMetaObject.connectSlotsByName(correction_factor_sheet3)

    def retranslateUi(self, correction_factor_sheet3):
        _translate = QtCore.QCoreApplication.translate
        correction_factor_sheet3.setWindowTitle(_translate("correction_factor_sheet3", "Correction factor"))
        self.correction_factor_sheet3_checkbox.setText(_translate("correction_factor_sheet3", "Using a correction factor for calculating adjusted evapotranspiration"))
        self.ok_equation_correction_factor_sheet3_push.setText(_translate("correction_factor_sheet3", "Ok"))
        self.groupBox.setTitle(_translate("correction_factor_sheet3", "equation"))
        self.label.setText(_translate("correction_factor_sheet3", "Please use the symbol \"x\" instead of the variable."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    correction_factor_sheet3 = QtWidgets.QMainWindow()
    ui = Ui_correction_factor_sheet3()
    ui.setupUi(correction_factor_sheet3)
    correction_factor_sheet3.show()
    sys.exit(app.exec_())
