# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Correction_factor_natural_evapotranspiration_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_correction_factor_naturalEva(object):
    def setupUi(self, correction_factor_naturalEva):
        correction_factor_naturalEva.setObjectName("correction_factor_naturalEva")
        correction_factor_naturalEva.resize(434, 263)
        correction_factor_naturalEva.setMinimumSize(QtCore.QSize(434, 263))
        correction_factor_naturalEva.setMaximumSize(QtCore.QSize(434, 263))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/title.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        correction_factor_naturalEva.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(correction_factor_naturalEva)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(7, 4, 421, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.correction_factor_naturalEva_checkbox = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.correction_factor_naturalEva_checkbox.sizePolicy().hasHeightForWidth())
        self.correction_factor_naturalEva_checkbox.setSizePolicy(sizePolicy)
        self.correction_factor_naturalEva_checkbox.setObjectName("correction_factor_naturalEva_checkbox")
        self.verticalLayout_2.addWidget(self.correction_factor_naturalEva_checkbox)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(12, 22, 381, 171))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.correction_factor_naturalEva_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.correction_factor_naturalEva_lineEdit.setObjectName("correction_factor_naturalEva_lineEdit")
        self.verticalLayout.addWidget(self.correction_factor_naturalEva_lineEdit)
        self.frame = QtWidgets.QFrame(self.layoutWidget_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.label = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_equation_correction_factor_naturalEva_push = QtWidgets.QPushButton(self.layoutWidget)
        self.ok_equation_correction_factor_naturalEva_push.setObjectName("ok_equation_correction_factor_naturalEva_push")
        self.horizontalLayout.addWidget(self.ok_equation_correction_factor_naturalEva_push)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        correction_factor_naturalEva.setCentralWidget(self.centralwidget)

        self.retranslateUi(correction_factor_naturalEva)
        QtCore.QMetaObject.connectSlotsByName(correction_factor_naturalEva)

    def retranslateUi(self, correction_factor_naturalEva):
        _translate = QtCore.QCoreApplication.translate
        correction_factor_naturalEva.setWindowTitle(_translate("correction_factor_naturalEva", "Correction Factor Natural Evapotranspiration"))
        self.correction_factor_naturalEva_checkbox.setText(_translate("correction_factor_naturalEva", "Using a correction factor for calculating adjusted evapotranspiration"))
        self.groupBox.setTitle(_translate("correction_factor_naturalEva", "equation"))
        self.label.setText(_translate("correction_factor_naturalEva", "Please use the symbol \"x\" instead of the variable."))
        self.ok_equation_correction_factor_naturalEva_push.setText(_translate("correction_factor_naturalEva", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    correction_factor_naturalEva = QtWidgets.QMainWindow()
    ui = Ui_correction_factor_naturalEva()
    ui.setupUi(correction_factor_naturalEva)
    correction_factor_naturalEva.show()
    sys.exit(app.exec_())
