# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Correction_factor_sheet1_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_correction_factor_sheet1(object):
    def setupUi(self, correction_factor_sheet1):
        correction_factor_sheet1.setObjectName("correction_factor_sheet1")
        correction_factor_sheet1.resize(447, 277)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(correction_factor_sheet1.sizePolicy().hasHeightForWidth())
        correction_factor_sheet1.setSizePolicy(sizePolicy)
        correction_factor_sheet1.setMinimumSize(QtCore.QSize(447, 277))
        correction_factor_sheet1.setMaximumSize(QtCore.QSize(447, 277))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/title.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        correction_factor_sheet1.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(correction_factor_sheet1)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(12, 12, 421, 251))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.correction_factor_sheet1_checkbox = QtWidgets.QCheckBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.correction_factor_sheet1_checkbox.sizePolicy().hasHeightForWidth())
        self.correction_factor_sheet1_checkbox.setSizePolicy(sizePolicy)
        self.correction_factor_sheet1_checkbox.setObjectName("correction_factor_sheet1_checkbox")
        self.verticalLayout_2.addWidget(self.correction_factor_sheet1_checkbox)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.widget1 = QtWidgets.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(12, 22, 381, 171))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.correction_factor_sheet1_lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.correction_factor_sheet1_lineEdit.setObjectName("correction_factor_sheet1_lineEdit")
        self.verticalLayout.addWidget(self.correction_factor_sheet1_lineEdit)
        self.frame = QtWidgets.QFrame(self.widget1)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.label = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_equation_correction_factor_sheet1_push = QtWidgets.QPushButton(self.widget)
        self.ok_equation_correction_factor_sheet1_push.setObjectName("ok_equation_correction_factor_sheet1_push")
        self.horizontalLayout.addWidget(self.ok_equation_correction_factor_sheet1_push)
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        correction_factor_sheet1.setCentralWidget(self.centralwidget)

        self.retranslateUi(correction_factor_sheet1)
        QtCore.QMetaObject.connectSlotsByName(correction_factor_sheet1)

    def retranslateUi(self, correction_factor_sheet1):
        _translate = QtCore.QCoreApplication.translate
        correction_factor_sheet1.setWindowTitle(_translate("correction_factor_sheet1", "Correction Factor"))
        self.correction_factor_sheet1_checkbox.setText(_translate("correction_factor_sheet1", "Using a correction factor for calculating adjusted evapotranspiration"))
        self.groupBox.setTitle(_translate("correction_factor_sheet1", "equation"))
        self.label.setText(_translate("correction_factor_sheet1", "Please use the symbol \"x\" instead of the variable."))
        self.ok_equation_correction_factor_sheet1_push.setText(_translate("correction_factor_sheet1", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    correction_factor_sheet1 = QtWidgets.QMainWindow()
    ui = Ui_correction_factor_sheet1()
    ui.setupUi(correction_factor_sheet1)
    correction_factor_sheet1.show()
    sys.exit(app.exec_())
