# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'correction_factor_sheet2_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Correction_factor_sheet2(object):
    def setupUi(self, Correction_factor_sheet2):
        Correction_factor_sheet2.setObjectName("Correction_factor_sheet2")
        Correction_factor_sheet2.resize(401, 268)
        Correction_factor_sheet2.setMinimumSize(QtCore.QSize(401, 268))
        Correction_factor_sheet2.setMaximumSize(QtCore.QSize(401, 268))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/title.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Correction_factor_sheet2.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Correction_factor_sheet2)
        self.centralwidget.setObjectName("centralwidget")
        self.correction_factor_sheet2_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.correction_factor_sheet2_checkbox.setGeometry(QtCore.QRect(10, 10, 351, 17))
        self.correction_factor_sheet2_checkbox.setObjectName("correction_factor_sheet2_checkbox")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(False)
        self.groupBox.setGeometry(QtCore.QRect(10, 34, 381, 201))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 21, 361, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.correction_factor_sheet2_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.correction_factor_sheet2_lineEdit.setObjectName("correction_factor_sheet2_lineEdit")
        self.verticalLayout.addWidget(self.correction_factor_sheet2_lineEdit)
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.ok_equation_correction_factor_sheet2_push = QtWidgets.QPushButton(self.centralwidget)
        self.ok_equation_correction_factor_sheet2_push.setGeometry(QtCore.QRect(10, 240, 75, 23))
        self.ok_equation_correction_factor_sheet2_push.setObjectName("ok_equation_correction_factor_sheet2_push")
        Correction_factor_sheet2.setCentralWidget(self.centralwidget)

        self.retranslateUi(Correction_factor_sheet2)
        QtCore.QMetaObject.connectSlotsByName(Correction_factor_sheet2)

    def retranslateUi(self, Correction_factor_sheet2):
        _translate = QtCore.QCoreApplication.translate
        Correction_factor_sheet2.setWindowTitle(_translate("Correction_factor_sheet2", "Correction Factor"))
        self.correction_factor_sheet2_checkbox.setText(_translate("Correction_factor_sheet2", "Using a correction factor for calculating adjusted evapotranspiration"))
        self.groupBox.setTitle(_translate("Correction_factor_sheet2", "equation"))
        self.label.setText(_translate("Correction_factor_sheet2", "Please use the symbol \"x\" instead of the variable."))
        self.ok_equation_correction_factor_sheet2_push.setText(_translate("Correction_factor_sheet2", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Correction_factor_sheet2 = QtWidgets.QMainWindow()
    ui = Ui_Correction_factor_sheet2()
    ui.setupUi(Correction_factor_sheet2)
    Correction_factor_sheet2.show()
    sys.exit(app.exec_())
