# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sheet_toolbox_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SheetToolbar(object):
    def setupUi(self, SheetToolbar):
        SheetToolbar.setObjectName("SheetToolbar")
        SheetToolbar.resize(337, 200)
        SheetToolbar.setMinimumSize(QtCore.QSize(337, 129))
        SheetToolbar.setMaximumSize(QtCore.QSize(337, 200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/title.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SheetToolbar.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(SheetToolbar)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 6, 318, 184))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.precipitation_toolbox = QtWidgets.QCommandLinkButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.precipitation_toolbox.sizePolicy().hasHeightForWidth())
        self.precipitation_toolbox.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.precipitation_toolbox.setIcon(icon1)
        self.precipitation_toolbox.setObjectName("precipitation_toolbox")
        self.verticalLayout.addWidget(self.precipitation_toolbox)
        self.Natural_Evapotranspiration_toolbox = QtWidgets.QCommandLinkButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Natural_Evapotranspiration_toolbox.sizePolicy().hasHeightForWidth())
        self.Natural_Evapotranspiration_toolbox.setSizePolicy(sizePolicy)
        self.Natural_Evapotranspiration_toolbox.setIcon(icon1)
        self.Natural_Evapotranspiration_toolbox.setObjectName("Natural_Evapotranspiration_toolbox")
        self.verticalLayout.addWidget(self.Natural_Evapotranspiration_toolbox)
        self.Evaporation_toolbox = QtWidgets.QCommandLinkButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Evaporation_toolbox.sizePolicy().hasHeightForWidth())
        self.Evaporation_toolbox.setSizePolicy(sizePolicy)
        self.Evaporation_toolbox.setIcon(icon1)
        self.Evaporation_toolbox.setObjectName("Evaporation_toolbox")
        self.verticalLayout.addWidget(self.Evaporation_toolbox)
        self.agricultral_toolbox = QtWidgets.QCommandLinkButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.agricultral_toolbox.sizePolicy().hasHeightForWidth())
        self.agricultral_toolbox.setSizePolicy(sizePolicy)
        self.agricultral_toolbox.setIcon(icon1)
        self.agricultral_toolbox.setObjectName("agricultral_toolbox")
        self.verticalLayout.addWidget(self.agricultral_toolbox)
        SheetToolbar.setCentralWidget(self.centralwidget)

        self.retranslateUi(SheetToolbar)
        QtCore.QMetaObject.connectSlotsByName(SheetToolbar)

    def retranslateUi(self, SheetToolbar):
        _translate = QtCore.QCoreApplication.translate
        SheetToolbar.setWindowTitle(_translate("SheetToolbar", "SheetToolbar"))
        self.precipitation_toolbox.setText(_translate("SheetToolbar", "Precipitation (Sheet One)"))
        self.Natural_Evapotranspiration_toolbox.setText(_translate("SheetToolbar", "Natural Evapotranspiration (Sheet One)"))
        self.Evaporation_toolbox.setText(_translate("SheetToolbar", "Evapotranspiration (Sheet Two)"))
        self.agricultral_toolbox.setText(_translate("SheetToolbar", "Agricultral Services (Sheet Three)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SheetToolbar = QtWidgets.QMainWindow()
    ui = Ui_SheetToolbar()
    ui.setupUi(SheetToolbar)
    SheetToolbar.show()
    sys.exit(app.exec_())
