# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_layer_table_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShowLayerTable(object):
    def setupUi(self, ShowLayerTable):
        ShowLayerTable.setObjectName("ShowLayerTable")
        ShowLayerTable.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ShowLayerTable)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.show_layer_table = QtWidgets.QTableWidget(self.centralwidget)
        self.show_layer_table.setObjectName("show_layer_table")
        self.show_layer_table.setColumnCount(0)
        self.show_layer_table.setRowCount(0)
        self.verticalLayout.addWidget(self.show_layer_table)
        self.show_layer_button = QtWidgets.QPushButton(self.centralwidget)
        self.show_layer_button.setObjectName("show_layer_button")
        self.verticalLayout.addWidget(self.show_layer_button)
        self.horizontalLayout.addLayout(self.verticalLayout)
        ShowLayerTable.setCentralWidget(self.centralwidget)

        self.retranslateUi(ShowLayerTable)
        QtCore.QMetaObject.connectSlotsByName(ShowLayerTable)

    def retranslateUi(self, ShowLayerTable):
        _translate = QtCore.QCoreApplication.translate
        ShowLayerTable.setWindowTitle(_translate("ShowLayerTable", "MainWindow"))
        self.show_layer_button.setText(_translate("ShowLayerTable", "SAVE AS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ShowLayerTable = QtWidgets.QMainWindow()
    ui = Ui_ShowLayerTable()
    ui.setupUi(ShowLayerTable)
    ShowLayerTable.show()
    sys.exit(app.exec_())
