# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tolerance_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tolerance_show(object):
    def setupUi(self, tolerance_show):
        tolerance_show.setObjectName("tolerance_show")
        tolerance_show.setWindowModality(QtCore.Qt.ApplicationModal)
        tolerance_show.resize(325, 120)
        tolerance_show.setMinimumSize(QtCore.QSize(325, 120))
        tolerance_show.setMaximumSize(QtCore.QSize(325, 126))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/title.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        tolerance_show.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(tolerance_show)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(8, 20, 308, 83))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tolerance_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tolerance_label.sizePolicy().hasHeightForWidth())
        self.tolerance_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tolerance_label.setFont(font)
        self.tolerance_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tolerance_label.setObjectName("tolerance_label")
        self.horizontalLayout.addWidget(self.tolerance_label)
        self.tolerance_linEdit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tolerance_linEdit.sizePolicy().hasHeightForWidth())
        self.tolerance_linEdit.setSizePolicy(sizePolicy)
        self.tolerance_linEdit.setObjectName("tolerance_linEdit")
        self.horizontalLayout.addWidget(self.tolerance_linEdit)
        self.checkBox_scenario_mode = QtWidgets.QCheckBox(self.widget)
        self.checkBox_scenario_mode.setObjectName("checkBox_scenario_mode")
        self.horizontalLayout.addWidget(self.checkBox_scenario_mode)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.round_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.round_label.sizePolicy().hasHeightForWidth())
        self.round_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.round_label.setFont(font)
        self.round_label.setObjectName("round_label")
        self.horizontalLayout_2.addWidget(self.round_label)
        self.round_linEdit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.round_linEdit.sizePolicy().hasHeightForWidth())
        self.round_linEdit.setSizePolicy(sizePolicy)
        self.round_linEdit.setObjectName("round_linEdit")
        self.horizontalLayout_2.addWidget(self.round_linEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tolerance_push_button = QtWidgets.QPushButton(self.widget)
        self.tolerance_push_button.setObjectName("tolerance_push_button")
        self.horizontalLayout_3.addWidget(self.tolerance_push_button)
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        tolerance_show.setCentralWidget(self.centralwidget)

        self.retranslateUi(tolerance_show)
        QtCore.QMetaObject.connectSlotsByName(tolerance_show)

    def retranslateUi(self, tolerance_show):
        _translate = QtCore.QCoreApplication.translate
        tolerance_show.setWindowTitle(_translate("tolerance_show", "Tolerance"))
        self.tolerance_label.setToolTip(_translate("tolerance_show", "<html><head/><body><p>Please specify the tolerance value. <span style=\"color:blue\">If you do not specify the tolerance value, it will be set to 0.2 (MCM) </span></p></body></html>"))
        self.tolerance_label.setText(_translate("tolerance_show", "Tolerance :"))
        self.tolerance_linEdit.setToolTip(_translate("tolerance_show", "<html><head/><body><p>Please specify the tolerance value. <span style=\"color:blue\">If you do not specify the tolerance value, it will be set to 0.2 (MCM) </span></p></body></html>"))
        self.checkBox_scenario_mode.setText(_translate("tolerance_show", "Scenario Mode"))
        self.round_label.setText(_translate("tolerance_show", "Round Number :"))
        self.round_linEdit.setToolTip(_translate("tolerance_show", "<html><head/><body><p>Please specify the tolerance value. <span style=\"color:blue\">If you do not specify the tolerance value, it will be set to 0.2 (MCM) </span></p></body></html>"))
        self.tolerance_push_button.setText(_translate("tolerance_show", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tolerance_show = QtWidgets.QMainWindow()
    ui = Ui_tolerance_show()
    ui.setupUi(tolerance_show)
    tolerance_show.show()
    sys.exit(app.exec_())
